apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: | 
    - userarn: arn:aws:iam::259979020371:user/ci-client
      username: ci-client
      groups:
        - system:masters

